<?php

add_action( 'acf/include_fields', function() {
	if ( ! function_exists( 'acf_add_local_field_group' ) ) {
		return;
	}

	acf_add_local_field_group( array(
	'key' => 'group_662a74cb7a26b',
	'title' => 'MU Auth',
	'fields' => array(
		array(
			'key' => 'field_662a8863eb9d6',
			'label' => 'Admins',
			'name' => 'auth_users',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => 'These users can access this WordPress site\'s dashboard and have full control to make changes to the site.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'row',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add User',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_662a886eeb9d7',
					'label' => 'MUNet',
					'name' => 'munet',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_662a8863eb9d6',
				),
				array(
					'key' => 'field_667c0e26df51e',
					'label' => 'Permissions Level',
					'name' => 'permissions_level',
					'aria-label' => '',
					'type' => 'select',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'choices' => array(
						'Administrator' => 'Administrator',
						'Editor' => 'Editor',
					),
					'default_value' => 'Administrator',
					'return_format' => 'value',
					'multiple' => 0,
					'allow_null' => 0,
					'ui' => 0,
					'ajax' => 0,
					'placeholder' => '',
					'parent_repeater' => 'field_662a8863eb9d6',
				),
			),
		),
		array(
			'key' => 'field_6663228344646',
			'label' => 'Site Visibility',
			'name' => 'site_visibility',
			'aria-label' => '',
			'type' => 'radio',
			'instructions' => 'You can limit access to public pages on this site.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'public' => 'Site is publicly available to all',
				'admins' => 'Only Registered Admins (listed above) should be able to access this site',
				'extras' => 'Registered Admins (listed above) and others added below should be able to access this site',
			),
			'default_value' => 'public',
			'return_format' => 'value',
			'allow_null' => 1,
			'other_choice' => 0,
			'layout' => 'vertical',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_6663231e44648',
			'label' => 'View Users',
			'name' => 'view_users',
			'aria-label' => '',
			'type' => 'repeater',
			'instructions' => 'These users can access this WordPress site\'s pages and post, but not the dashboard.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6663228344646',
						'operator' => '==',
						'value' => 'extras',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layout' => 'row',
			'pagination' => 0,
			'min' => 0,
			'max' => 0,
			'collapsed' => '',
			'button_label' => 'Add User',
			'rows_per_page' => 20,
			'sub_fields' => array(
				array(
					'key' => 'field_6663232b44649',
					'label' => 'MUNet',
					'name' => 'munet',
					'aria-label' => '',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'maxlength' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'parent_repeater' => 'field_6663231e44648',
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'acf-options-mu-auth-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
) );
} );
